### ISSUE TITLE
3 questions: npm, cdn, utf

### ISSUE THREAD

**Issue by cekvenich** [karanlyons/murmurHash3.js#9]
1. Is there an es5 pre-built .js file that I can use? (vis jsdeliver CDN that just 'copies' github/npm').
I don't want to have to build es5, I just want to use it.

2. what is eta of npm? (it could be just name + 'karan' prefix)

3. ASCII only? other implementations are explicit that they are ascii only. Is this utf-8?

**Comment by karanlyons** [comment]
1. There would be in the actual release, which builds a `.js` and a `.d.ts` file as is TS-on-npm tradition. Since this is an artifact it’s not committed to the repo.
2. I’m not prefixing because older versions of this repo have already been packaged up and put on npm under more SEO friendly names. I’m working on getting one of those names transferred, but it’s by necessity a lower priority than my day to day job.
3. mmH3.js supports *any* data, as either strings or `Uint8Array`s. If you give it a javascript string it will decode it into UTF-8 bytes and hash that. Hence the reliance on `TextEncoder` et al. You can also see the tests for further proof of this support.

**Comment by cekvenich** [comment]
Thanks you for a response. #1 is a problem and any **against** tradition anywhere. The tradition is to allow github or npm to be accessed via CDN(eg jsdeliver). The developers use es5 libs in browsers that they don't build and get from a CDN, happy to give you lists of popular libs and the link to their es5.js in the repo so that it can be used by a CDN.

**Comment by karanlyons** [comment]
You wouldn’t have a problem with the npm release, which has a `.js` and a `.d.ts` file, the former being “vanilla” javascript, and the latter being type definitions for use in a typescript project.

As this is the source code repo and the project is written in typescript, the build artifacts aren’t committed to it, in the same way that executable binaries wouldn’t (normally) be committed to a C repo.

Also, with regards to things like jsdelivr, there’s now “allowing” on my end that I would be aware of: GitHub, npm, etc. are publicly accessible resources and a “CDN+transpiler as a Service” platform has no barriers to accessing and doing whatever they’d like with the files hosted by these resources.

I’m not sure what you mean by `es5.js` here. ECMAScript5 is a versioned standard of javascript. This project targets ES2015 and not ES2009 as the latter lacks features necessary for this library to work correctly. But polyfills are available for the features ES2009 lacks if you’re sure you need to be targeting such an old standard. [I’d hope that you don’t, though.](https://caniuse.com/#search=typedarray)

**Comment by cekvenich** [comment]
Oh  OK, So the npm release will contain the es5 js. THANKS!
